### ISSUE TITLE
GUIDE: Setting up a Discord server with SourceCred and GitHub actions

### ISSUE THREAD

**Issue by yeqbfgxjiq** [helpdao/TheSource#3]
This guide is being maintained in the AraCred GitHub org

https://github.com/aracred/TheSource/issues/3

**Comment by burrrata** [comment]
> Note!

You'll still need to configure `project.json` to point to your Discord server, user names, and GitHub repos

**Comment by yeqbfgxjiq** [comment]
This guide is outdated. Please refer to Aracred in the future

https://aracred.github.io/website/docs/deploymentOverview/#step-3-connect-discord-optional
